# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestElectionselenium():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_electionselenium(self):
    self.driver.get("https://www.croxyproxy.com/")
    self.driver.set_window_size(2560, 1330)
    self.driver.find_element(By.ID, "url").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "url").send_keys("https://secimharitasi.com/aday)
    self.driver.find_element(By.ID, "requestSubmit").click()
    self.driver.find_element(By.LINK_TEXT, "Oy Ver").click()
  
