from lib2to3.pgen2 import driver
from selenium import webdriver
import time
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

for i in range(200):
    driver=webdriver.Chrome()
    url="https://www.croxyproxy.com/"
    driver.get(url)
    print(driver.title)
    #driver.maximize_window()
    #driver.execute_script("window.scrollTo(0,0)")
    driver.find_element(By.ID, "url").send_keys("https://secimharitasi.com/aday/nahit-baykara-780")
    driver.find_element(By.ID, "requestSubmit").click()
    time.sleep(16)
    driver.find_element(By.LINK_TEXT, "Oy Ver").click()
    time.sleep(1)
    driver.close()